version: '3.7'

services:
  # Main PHP application
  app:
    image: todo-list-app
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-81c7bd7cb0ea62ce6e3506096326b5be}
      DATABASE_DSN: ${APP_DATABASE_DSN:-postgres://postgres:postgres@db:5432/todo-list?serverVersion=13.2}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    volumes:
      - ./app:/var/www/app:rw,cached
    networks:
      - app

  # Public HTTP server
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./app/public:/var/www/app/public:ro
      - ${DOCKER_VOLUME_NGINX_CONF_PATH:-./config/nginx/conf.d}:/etc/nginx/conf.d:ro,cached
    networks:
      - app

  # Main database
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-todo-list}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432
    networks:
      - app

volumes:
  db-data:

networks:
  app:
